#!/bin/bash
# guru-cli adapter generated by core // or installer?

module="audio"
script="audio.sh"
target="$GURU_BIN/$module/$script"
gr.debug "${0##*/}: adapting $script to $target with wariables \$@"

source "$target"
$module.main $@