#!/bin/bash
# grbl adapter generated by core Sat Sep  6 08:13:41 PM EEST 2025
source "/home/casa/bin/audio/radio.sh"
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    gr.debug "${0##*/}: adapting radio to /home/casa/bin/audio/radio.sh with variables $@"
    radio.main "$@"
fi
