#!/bin/bash
target="$HOME/Desktop/Freesi-Diagnostic.desktop"
echo "[Desktop Entry]" >$target
echo "Comment=Freesi network and device diagnostic and set up tool" >>$target
echo "Terminal=true" >>$target
echo "Name=Freesi Diagnostics" >>$target
echo "Exec=bash $HOME/diagnostics/run" >>$target
echo "Icon=$HOME/diagnostics/images/freesituuli-darkgray.png" >>$target
echo "Type=Application" >>$target
chmod +x $target
echo "Launcher created to desktop"