#!/bin/bash

pause(){
 read -n1 -rsp $'Press any key end the test or Ctrl+C to to leave it background...\n'
}



if [ -z $2 ]
then 
    testid=quick_test
else
    testid=$2
fi


profile="$1"
cfgDir="../cfg" 
cfgFile="aqc-$profile.cfg" 

# Check config folder
if [ ! -d "$cfgDir" ]; then 
    # Change to defualt folder
    cfgDir="/home/casa/git/install/laptop-tools/cfg" 
fi

datasource="$cfgDir/$cfgFile"

# Check profile file
if [ ! -f "$datasource" ]; then 
    echo "Profile $datasource not exist"
fi

# Check temporary config file
if [ -f server-$profile.cfg ]; then
    rm server-$profile.cfg
fi

text=$(cat "$datasource" |grep "host")
echo "${text// /}" >>server-$profile.cfg

text=$(cat "$datasource" |grep "port")
echo "${text// /}" >>server-$profile.cfg

text=$(cat "$datasource" |grep "user")
echo "${text// /}" >>server-$profile.cfg

text=$(cat "$datasource" |grep "password")
echo "${text// /}" >>server-$profile.cfg

text=$(cat "$datasource" |grep "cuid")
echo "${text// /}" >>server-$profile.cfg

. ./server-$profile.cfg
rm server-$profile.cfg 

echo "host: $host"
#echo "user: $user"
#echo "password: $password"
#echo "port: $port"
echo "cuid: $cuid"
server="-u $user -P $password -h $host -p $port"
mosquitto_sub -t $cuid/+/19/Value  $server -v 
#killall mosquitto_sub


