#!/bin/bash
temp=/tmp/diagnostics
target=$HOME/diagnostics ## code review 1.TODO: file plasing Issue #1
location=$(pwd)

pause(){
 read -n1 -rsp $'Press any key to continue or Ctrl+C to stop \n'
}

make_clean() {
	rm -rf $target/*
	cp -r $temp/diagnostics/* $target/ 
}

echo "updating installer tools"
mkdir $temp
mkdir $target
cd $temp
git clone -b master git clone https://ujoguru@bitbucket.org/ugdev/giocon.client.git && make_clean
cd $location
rm -rf $temp 
#echo 'Update ready, type "./run" to relaunch'
bash $target/run 