#!/bin/bash
temp=/tmp/tool-update
target=$HOME/tools
location=$(pwd)

pause(){
 read -n1 -rsp $'Press any key to continue or Ctrl+C to stop \n'
}

make_clean() {
	rm -rf $target/*
	cp -r $temp/laptop-tools/* $target/ 
}

echo "updating installer tools"
mkdir $temp
mkdir $target
cd $temp
git clone -b master https://ujoguru@bitbucket.org/freesi/laptop-tools.git && make_clean
cd $location
rm -rf $temp 
echo 'Update ready, type "./run" to relaunch'
bash $target/run 